# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lamoti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lamoti

  # Auto Layout
  pod 'SnapKit'
  
  # Image
  pod 'Kingfisher'
  
  # UI
  pod 'TextFieldEffects'
  
  # Object <-> JSON
  pod 'ObjectMapper'
  
  # HTTP Networking ( base URLSession )
  pod 'Alamofire'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  

end
