# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lamoti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lamoti

  # Auto Layout
  pod 'SnapKit', '~> 5.0.0'
  
  # UI
  pod 'TextFieldEffects'
  
  # Object <-> JSON
  pod 'ObjectMapper'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  

end
